face_recog/accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('', views.home, name="home"),
    path('facerecog/', views.facerecog, name = "facerecog"),
    path('teacherRegister/', views.teacherRegister, name="teacherRegister"),
    path('studentRegister/', views.studentRegister, name="studentRegister"),
    path('teacherLogin/', views.teacherLogin, name="teacherLogin"),
    path('studentLogin/', views.studentLogin, name="studentLogin"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('student_dashboard/', views.student_dashboard, name="student_dashboard"),
    path('account/', views.accountSettings, name="account"),
    path('studentaccount/', views.StudentaccountSettings, name="studentaccount"),
    # path('dashboard/<str:pk>/', views.dashboard, name="dashboard"),
    # path('register/', views.registerPage, name="register"),
    # path('login/', views.loginPage, name="login"),
    # path('logout/', views.logoutUser, name="logout"),
    # path('account/', views.accountSettings, name="account"),
]

face_recog/face_recog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

face_recog/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class Student(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE )
    name = models.CharField(max_length=120, null=True, blank=False)
    phone = models.CharField(max_length=10, null=True, blank=False)
    email = models.CharField(max_length=120, null=True, blank=False)
    profile_pic = models.ImageField(default="profile_photo.png", null=True, blank=True)

class Teacher(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE )
    name = models.CharField(max_length=120, null=True, blank=False)
    phone = models.CharField(max_length=120, null=True, blank=False)
    email = models.CharField(max_length=120, null=True, blank=False)
    profile_pic = models.ImageField(default="profile_photo.png", null=True, blank=True)

# Create your models here.
# class Attendance(models.Model):
    

face_recog/accounts/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User 
from django import forms
from django.core.validators import RegexValidator
from .models import *

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = '__all__'  
        exclude = ['User']

class TeacherForm(ModelForm):
    class Meta:
        model = Student
        fields = '__all__'  
        exclude = ['User']

face_recog/accounts/views.py
import os
import face_recognition


from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import Group

from .models import *
from .forms import *
# from .decorators import allowed_users
# from .filters import OrderFilter 
import js2py

from temp import *

from Naked.toolshed.shell import execute_js, muterun_js


def home(request):

    context = {}
    return render(request, 'homePage.html', context )

def teacherRegister(request):

    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user=form.save()
            Teacher.objects.create(
                user=user
            )

            return redirect('teacherLogin')

    context = {'form':form}
    return render(request, 'teacher_register.html', context )

def studentRegister(request):

    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user=form.save()
            Student.objects.create(
                user=user
            )

            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(request, username=username, password=password )

            login(request, user)

            return redirect('student_dashboard')

            # return redirect('teacherLogin')

    context = {'form':form}
    return render(request, 'student_register.html', context )

def teacherLogin(request):
    

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)

            return redirect('dashboard')

    context = {}
    return render(request, 'teacher_login.html', context )

def studentLogin(request):

    context = {}
    return render(request, 'student_login.html', context )

def dashboard(request):

    context = {}
    # return render(request, 'dashboard.html', context )
    return redirect('http://localhost:3000/')

def student_dashboard(request):

    context = {}
    return render(request, 'student_dashboard.html', context )

def accountSettings(request):
    teacher = request.user.teacher
    form = TeacherForm(instance=teacher)

    if request.method == 'POST':
        form = TeacherForm(request.POST, request.FILES, instance=teacher)
        if form.is_valid():
            form.save()
            
    context = {'form':form}
    return render(request, 'teacher_account_settings.html', context)

def StudentaccountSettings(request):
    student = request.user.student
    form = StudentForm(instance=student)

    if request.method == 'POST':
        form = StudentForm(request.POST, request.FILES, instance=student)
        if form.is_valid():
            form.save()
            
    context = {'form':form}
    return render(request, 'account_settings.html', context)

# def loginPage(request):

#     context = {}
#     return render(request, 'login.html', context )

def facerecog(request):
    
    with open('database.db') as f:
        data = f.read()


    x = data.split("$");

    y = data.split("%");

    #print(y[len(y)-2])
    #print(x[len(x)-2])

    latestimage = "tobeverified/" + x[len(x)-2]
    image = face_recognition.load_image_file(latestimage)
    encoding1 = face_recognition.face_encodings(image)[0]


    dir_path = 'static/images'

    count = 0
    const2 = -3;

    for path in os.listdir(dir_path):
        if os.path.isfile(os.path.join(dir_path, path)):
            print(path)
            image2 = face_recognition.load_image_file(f"static/images/{path}")
            
            if len(face_recognition.face_encodings(image2)) != 0:
                encoding2 = face_recognition.face_encodings(image2)[0]

                if (face_recognition.compare_faces([encoding1], encoding2) == [True]):
                    print("welcome", y[len(y)-2])
                    # return HttpResponse("Welcome")
                    const2 = 0;
                    context = {'name' : y[len(y)-2]}
                    with open('database.db', 'w') as f:
                        pass
                    os.remove(f'{latestimage}')
                    return render(request, 'welcome.html', context )
                    
                    break

            
            


            #print(type(face_recognition.compare_faces([encoding1], encoding2)))
            
            else:
                continue


            

    if(const2 != 0):
        with open('database.db', 'w') as f:
            pass
        os.remove(f'{latestimage}')
        return HttpResponse('Not Verified')

    

face_recog/templates/account_settings.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Page Title</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' href="{% static 'css/settings.css' %}">
    {% comment %} <script src='main.js'></script> {% endcomment %}
</head>
<body>
    <header>
        <h1 class="name">Look<span class="py">Up</span></h1>
        <nav>
            <div class="left">
                <a href="{% url 'home' %}">Home</a>
            </div>
            <div class="left">
                <a href="#">About us</a>
            </div>
            <div class="left">
                <a href="#">Help</a>
            </div>
            <div class="left">
                <a href="#">Settings</a>
            </div>
        </nav>
    </header>

    <div class="accountHead">
        <h1>Account Details</h1>
    </div>
    <style>
        .profile-pic {
            width: 200px;
            height: 200px;
            margin-left: 200px;
            border-radius: 50%;
        }
        .row{
            border-radius: 6px;
            height: 550px;
            width : 500px;
            border: 1px solid #CACACA;
            background: #fff;
            margin-left: 500px;
        }

        p{
            color: rgb(4, 40, 117);
            padding-left: 30px;
            font-size: 18px;
        }

        p a{
            text-decoration: none;
        }

        label{
            font-size: 20px;
            color: rgb(39, 39, 157);
            font-weight: bold;
            padding-right: 20px;
            /* border: solid grey; */
        }

        #id_name{
            font-size: 15px;
            height: 30px;
            border: solid rgb(233, 228, 228);
            width: 360px;
            border-radius: 10px;
            text-align: center;
        }

        #id_phone{
            font-size: 15px;
            height: 30px;
            border: solid rgb(233, 228, 228);
            width: 358px;
            border-radius: 10px;
            text-align: center;
        }

        #id_email{
            font-size: 15px;
            height: 30px;
            border: solid rgb(233, 228, 228);
            width: 360px;
            border-radius: 10px;
            text-align: center;
        }

        select{
            font-size: 15px;
            margin-left: 10px;
            align-items: center;
            text-align: center;
            height: 35px;
            width: 370px;
            border: solid rgb(233, 228, 228);
            border-radius: 10px;
        }

        option{
            border: solid rgb(233, 228, 228);
        }

        input[type="file"]{
            width: 270px;
        }

        ::-webkit-file-upload-button{
            margin-left: 0px;
            border: transparent;
            cursor: pointer;
        }

        #id_profile_pic{
            margin-left: 30px;
            height: 30px;
            width: 260px;
        }
    </style>
    
    <br>
    <div class="row">       
        <div class="col-md-3">
            <div class="card card-body">
                <img class="profile-pic" src="{{request.user.student.profile_pic.url}}">
    
            </div>
        </div>
        <div class="col-md-9">
            <div class="card card-body">
    
                <form method="POST" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form.as_p}}
    
                    <input class="btn btn-primary" type="submit" name="Update Information" style="width: 380px; height: 40px; margin-left: 60px; font-size: 25px; background-color: rgb(185, 184, 184); border-radius: 10px; border: transparent;text-align: center;">
                </form>
            </div>
        </div>
    </div>
</body>
</html>

face_recog/templates/dashboard.html
<h1>dashboard</h1>

<p>Hi {{ request.user }}</p>

<span><a href="{% url 'account' %}">Settings</a></span>

face_recog/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <span><a href="{% url 'teacherLogin' %}">Teacher</a></span>
    <br>
    <span><a href="{% url 'studentRegister' %}">Student</a></span>    
</body>
</html>

face_recog/templates/homePage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'css/homePage.css' %}">
</head>
<body>
    <header>
        <h1 class="name">Look<span class="py">Up</span></h1>
        <nav>
            <div class="left">
                <a href="{% url 'home' %}">Home</a>
            </div>
            <div class="left">
                <a href="#">About us</a>
            </div>
            <div class="left">
                <a href="#">Help</a>
            </div>
            <div class="left">
                <a href="#">Settings</a>
            </div>
        </nav>
    </header>
    <div class="backgroundCont">
        <div class="keep">
            <div class="user-box">
                <div class="user">
                    User
                </div>
                <div class="teacher">
                    <button > <a href="{% url 'teacherLogin' %}">Teacher</a>
                        <img src="static/images/teach.png" alt="Teacher-icon" id="teacherIcon">
                        </button>
                </div>
                <div class="student">
                    <button>
                        <a href="{% url 'studentRegister' %}">Student</a>
                        <img src="static/images/studentIcon.jpg" alt="student-icon" id="studentIcon">
                    </button>
                </div>
            </div>
        </div>
    </div>
    
</body>
</html>

face_recog/templates/login.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nabla&family=Poppins&display=swap" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
</head>
<body>

    <header>
        <h1 class="name">Look<span class="py">Up</span></h1>
        <nav>
            <div class="left">
                <a href="{% url 'home' %}">Home</a>
            </div>
            <div class="left">
                <a href="#">About us</a>
            </div>
            <div class="left">
                <a href="#">Help</a>
            </div>
            <div class="left">
                <a href="#">Settings</a>
            </div>
        </nav>
    </header>
    <section class="container forms">
        <div class="form login">
            <div class="form-content">
                <p>Login</p>

                <form action="#">
                    <div class="field input-field">
                        <input type="email" placeholder="Email" class="input">
                    </div>
                    <div class="field input-field">
                        <input type="password" placeholder="Password" class="password">
                        <i class="bx bx-hide eye-icon"></i>
                    </div>
                    <div class="form-link">
                        <a href="#" class="forgot-pass">Forgot password?</a>
                    </div>
                    <div class="field button-field">
                        <button>Login</button>
                    </div>
                    <div class="form-link">
                        <span>Not Registered?<a href="signup">SignUp</a></span>
                    </div>
                </form>
            </div>
        </div>

        <!--SIGN UP-->
        {% comment %} <div class="form signup">
            <div class="form-content">
                <p>SignUp</p>

                <form action="#">
                    <div class="field input-field">
                        <input type="email" placeholder="Email" class="input">
                    </div>
                    <div class="field input-field">
                        <input type="password" placeholder="Password" class="password">
    
                    </div>
                    <div class="field input-field">
                        <input type="password" placeholder="Confirm Password" class="password">
                        <i class="bx bx-hide eye-icon"></i>
                    </div>
                    
                    <div class="field button-field">
                        <button>SignUp</button>
                    </div>
                    <div class="form-link">
                        <span>Already have an account?<a href="#" class="link login-link">login</a></span>
                    </div>
                </form>
            </div>
        </div>
    </section>

    <script src="{% static '/js/login.js' %}"></script> {% endcomment %}
    
    
</body>
</html>

face_recog/templates/notverified.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1> Not Verified </h1>
    
</body>
</html>

face_recog/templates/signup.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nabla&family=Poppins&display=swap" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
</head>
<body>

    <header>
        <h1 class="name">Look<span class="py">Up</span></h1>
        <nav>
            <div class="left">
                <a href="{% url 'home' %}">Home</a>
            </div>
            <div class="left">
                <a href="#">About us</a>
            </div>
            <div class="left">
                <a href="#">Help</a>
            </div>
            <div class="left">
                <a href="#">Settings</a>
            </div>
        </nav>
    </header>
    <section class="container forms">
        <div class="form login">
            <div class="form-content">
                <p>SignUp</p>

                <form action="#">
                    <div class="field input-field">
                        <input type="email" placeholder="Email" class="input">
                    </div>
                    <div class="field input-field">
                        <input type="password" placeholder="Password" class="password">
                    </div>
                    <div class="field input-field">
                        <input type="password" placeholder="Confirm Password" class="password">
                        <i class="bx bx-hide eye-icon"></i>
                    </div>
                    {% comment %} <div class="form-link">
                        <a href="#" class="forgot-pass">Forgot password?</a>
                    </div> {% endcomment %}
                    <div class="field button-field">
                        <button>SignUp</button>
                    </div>
                    <div class="form-link">
                        <span>Already Registered?<a href="../login.html">Login</a></span>
                    </div>
                </form>
            </div>
        </div>

        <!--SIGN UP-->
        {% comment %} <div class="form signup">
            <div class="form-content">
                <p>SignUp</p>

                <form action="#">
                    <div class="field input-field">
                        <input type="email" placeholder="Email" class="input">
                    </div>
                    <div class="field input-field">
                        <input type="password" placeholder="Password" class="password">
    
                    </div>
                    <div class="field input-field">
                        <input type="password" placeholder="Confirm Password" class="password">
                        <i class="bx bx-hide eye-icon"></i>
                    </div>
                    
                    <div class="field button-field">
                        <button>SignUp</button>
                    </div>
                    <div class="form-link">
                        <span>Already have an account?<a href="#" class="link login-link">login</a></span>
                    </div>
                </form>
            </div>
        </div>
    </section>

    <script src="{% static '/js/login.js' %}"></script>
     {% endcomment %}
    
</body>
</html>

face_recog/templates/student_dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/settings.css' %}">
</head>
<body>
    <style>
        .myHeading{
            height: 100px;
            width: 100%;
            background-color: grey;
            text-align: center;
        }
        .myHeading h1{
            padding-top: 10px;
            margin-top: 0px;
            font-size: 50px;
        }

        .remaining{
            background-color: rgb(234, 234, 234);
            height: 542px;
            width: 100%;
        }
        .remaining p{
            margin-top: 0px;
        }

        .updateButton{
            height: 100px;
            width: 350px;
            padding: 15px 25px;
            font-size: 30px;
            text-align: center;
            cursor: pointer;
            outline: none;
            color: #fff;
            background-color: #0430aa;
            border: none;
            border-radius: 15px;
            box-shadow: 0 9px #999;
            margin-left: 600px;
            margin-top: 100px;
            font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
        }

        .updateButton:hover {background-color: #07bddd}

        .updateButton:active {
            background-color: #35bdeb;
            box-shadow: 0 5px #666;
            transform: translateY(4px);
        }
        .updateButton a{
            text-decoration: none;
            color: white;
        }


    </style>
    <header>
        <h1 class="name">Look<span class="py">Up</span></h1>
        <nav>
            <div class="left">
                <a href="{% url 'home' %}">Home</a>
            </div>
            <div class="left">
                <a href="#">About us</a>
            </div>
            <div class="left">
                <a href="#">Help</a>
            </div>
            <div class="left">
                <a href="#">Settings</a>
            </div>
        </nav>
    </header>
    <!-- <h1>student dashboard</h1> -->
    <div class="myHeading">
        <h1>Registered as {{request.user}}!!</h1>
    </div>
    <div class="remaining">
        <marquee direction="right" behavior="alternate" style="border:transparent ; height: 100px; font-size: 40px; padding-top: 20px; color: rgb(153, 79, 6);font-family: cursive;">
            Update your profile.
        </marquee>
        <button class="updateButton"><a href="{% url 'studentaccount' %}">Go to profile</a></button>
        
    </div>

    
     
   
</body>
</html>

face_recog/templates/student_login.html
<!-- <h1>Student Login</h1>

<p>Have not made an account yet ?</p>
<span><a href="{% url 'studentRegister' %}">Sign up</a></span> -->

face_recog/templates/student_register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/homePage.css' %}">
</head>
<body>
    <header>
        <h1 class="name">Look<span class="py">Up</span></h1>
        <nav>
            <div class="left">
                <a href="{% url 'home' %}">Home</a>
            </div>
            <div class="left">
                <a href="#">About us</a>
            </div>
            <div class="left">
                <a href="#">Help</a>
            </div>
            <div class="left">
                <a href="#">Settings</a>
            </div>
        </nav>
    </header>

    <section class="container forms">
        <div class="form login">
            <div class="form-content">
                <p>Register</p>
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="containingBox">
                        <div class="input-group mb-3">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>
                            </div>
                            {{form.username}}
                        </div>
                    </div>
                    
                    <div class="containingBox">
                        <div class="input-group mb-2">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
                            </div>
                            {{form.email}}
                        </div>
                    </div>

                    <div class="containingBox">
                        <div class="input-group mb-2">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                            </div>
                            {{form.password1}}
                        </div>
                    </div>
                    
                    <div class="containingBox">
                        <div class="input-group mb-2">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                            </div>
                            {{form.password2}}
                        </div>
                    </div>
            
                    <div class="d-flex justify-content-center mt-3 login_container">
                        <input class="button" type="submit" value="Register Account">
                    </div>
                </form>
            

            </div>
        </div>
    </section>

    <script>
    var form_fields = document.getElementsByTagName('input')
    form_fields[1].placeholder='Username..';
    form_fields[2].placeholder='Email..';
    form_fields[3].placeholder='Enter password...';
    form_fields[4].placeholder='Re-enter Password...';


    for (var field in form_fields){	
    form_fields[field].className += ' form-control'
    }
    </script>
    </body>
</html>

face_recog/templates/teacher_account_settings.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Page Title</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' href="{% static 'css/settings.css' %}">
    {% comment %} <script src='main.js'></script> {% endcomment %}
</head>
<body>
    <header>
        <h1 class="name">Look<span class="py">Up</span></h1>
        <nav>
            <div class="left">
                <a href="{% url 'home' %}">Home</a>
            </div>
            <div class="left">
                <a href="#">About us</a>
            </div>
            <div class="left">
                <a href="#">Help</a>
            </div>
            <div class="left">
                <a href="#">Settings</a>
            </div>
        </nav>
    </header>

    <div class="accountHead">
        <h1>Account Details</h1>
    </div>
    <style>
        .profile-pic {
            width: 200px;
            height: 200px;
            margin-left: 200px;
            border-radius: 50%;
        }
        .row{
            border-radius: 6px;
            height: 550px;
            width : 500px;
            border: 1px solid #CACACA;
            background: #fff;
            margin-left: 500px;
        }

        p{
            color: rgb(4, 40, 117);
            padding-left: 30px;
            font-size: 18px;
        }

        p a{
            text-decoration: none;
        }

        label{
            font-size: 20px;
            color: rgb(39, 39, 157);
            font-weight: bold;
            padding-right: 20px;
            /* border: solid grey; */
        }

        #id_name{
            font-size: 15px;
            height: 30px;
            border: solid rgb(233, 228, 228);
            width: 360px;
            border-radius: 10px;
            text-align: center;
        }

        #id_phone{
            font-size: 15px;
            height: 30px;
            border: solid rgb(233, 228, 228);
            width: 358px;
            border-radius: 10px;
            text-align: center;
        }

        #id_email{
            font-size: 15px;
            height: 30px;
            border: solid rgb(233, 228, 228);
            width: 360px;
            border-radius: 10px;
            text-align: center;
        }

        select{
            font-size: 15px;
            margin-left: 10px;
            align-items: center;
            text-align: center;
            height: 35px;
            width: 370px;
            border: solid rgb(233, 228, 228);
            border-radius: 10px;
        }

        option{
            border: solid rgb(233, 228, 228);
        }

        input[type="file"]{
            width: 270px;
        }

        #id_profile_pic{
            margin-left: 30px;
            height: 30px;
            width: 260px;
        }
    </style>
    
    <br>
    <div class="row">       
        <div class="col-md-3">
            <div class="card card-body">
                <img class="profile-pic" src="{{request.user.teacher.profile_pic.url}}">
    
            </div>
        </div>
        <div class="col-md-9">
            <div class="card card-body">
    
                <form method="POST" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form.as_p}}
    
                    <input class="btn btn-primary" type="submit" name="Update Information" style="width: 380px; height: 40px; margin-left: 60px; font-size: 25px; background-color: rgb(185, 184, 184); border-radius: 10px; border: transparent;text-align: center;">
                </form>
            </div>
        </div>
    </div>
</body>
</html>